### PR TITLE
fix: add IME input support to the composition input

### LINKED ISSUE #438: Cannot input Chinese character to message textbox with some IME (e.g. Rime)
**Describe the bug**
Cannot input Chinese character to message textbox with some IME (e.g. Rime)

**To Reproduce**
using Rime, just typing some Chinese character, then enter but nothing happened;
If you type some English letters first, then switch to Rime, type any key, there will be letters copied and pasted as blow.

**Screenshots or Logs**
pwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwopwwo

**Other information (please complete the following information):**
The issue is only in the message textbox, other textboxes are OK.

* Device: PC
* OS: Windows 10
* Session Version: v1.10.1 and previous version

### LINKED ISSUE #584: Unable to convert Japanese text input using IME on PC (Linux)
**Describe the bug**
When inputting Japanese text, I am unable to convert input from Hiragana to Kanji or Katakana. Normally, when inputting Japanese via the IME the text is highlighted, at which point using the space key allows for selection of different Kanji/Katakana/etc variations on the word and the Enter key confirms, like so:

normal_input

With Session Desktop, however, pressing space after input does not open the standard IME selection menu, but simply puts the raw Hiragana into the text field with no ability to change it, like so:
Screenshot from 2021-12-25 18-34-43
Screenshot from 2021-12-25 18-35-44

Being unable to input Kanji, and only being able to input Hiragana, makes communication in Japanese somewhat difficult. The only existing workaround is to type out the sentence in gedit or another writing tool, then copy-paste it into Session's input field. This behavior has been reported by at least two other users in a Japanese language Open Group I use. I believe in both cases it was Linux, though I do not at present know which distro or any other version information for Session Desktop or their IME.

It is worth noting, that the same account logged in via Session Android has no difficult with Japanese IME. This behavior seems isolated to the Desktop version.

**To Reproduce**
Use a Japanese IME to input text in Session Desktop. Hit space after typing in Hiragana text, resulting in raw Hiragana input (no ability to convert to Kanji or Katakana etc).

**Screenshots or Logs**
see above

**Other information (please complete the following information):**

* Device: PC
* OS: Ubuntu 20.04.3 LTS
* IME Details: ibus-anthy
* Session Version or Git commit hash: Session v1.7.6

### LINKED ISSUE #840: Mistakenly send message twice in non-English language
**Describe the bug**
When sending message in Japanese, we have to type Enter 2 times.
1. confirm conversion
2. send message

You don't have to confirm conversion in English. But other languages such as Japanese and Korean, we have to type Enter key and confirm conversion. At that time, the message is sent by mistake. In order to support other language, please fix this bug.

**To Reproduce**
Use Japanese IME

**Screenshots or Logs**
Videotogif

**To fix**
To detect if users are typing or not,  you can use `compositionstart` and `compositionend` event in Javascript.

### LINKED ISSUE #1518: [BUG] IME input issue for composed language input methods in V1.16.4
Chinese Pinyin input in WINDOWS outputs repeated English letters instead of intended Chinese characters

### PR DESCRIPTION
**Pull request by Aerilym**
fixes #1518 

This should also fix:
resolves #438
resolves #840 
resolves #584

### CODE REVIEW

File: ts/hooks/useDebuncedSpellcheck.ts [hunk 1]
```diff
@@ -6,14 +6,72 @@ interface DebouncedSpellcheckProps {
...
+
+  const hideSpellcheckLines = useCallback(() => {
+    elementRef.current?.classList.add('spellcheck-hidden');
+  }, [elementRef]);
+
+  const showSpellcheckLines = useCallback(() => {
+    elementRef.current?.classList.remove('spellcheck-hidden');
   }, [elementRef]);
 
   // eslint-disable-next-line react-hooks/exhaustive-deps -- TODO: see if we can create our own useDebounce hook
```
Comment (Bilb) [inline ts/hooks/useDebuncedSpellcheck.ts:72]: // eslint-disable-next-line react-hooks/exhaustive-deps -- TODO: see if we can create our own useDebounce hook
I don't thnk we still need this comment? nor the eslint-disable-next-line

File: ts/hooks/useDebuncedSpellcheck.ts [hunk 2]
```diff
@@ -6,14 +6,72 @@ interface DebouncedSpellcheckProps {
...
+  }
+
+  .spellcheck-hidden::spelling-error {
+    text-decoration: none !important;
+  }
+
+  .spellcheck-hidden::grammar-error {
+    text-decoration: none !important;
+  }
+`;
```
Comment (Bilb) [inline ts/hooks/useDebuncedSpellcheck.ts:37]: you don't think we should add this to `global.css` instead?
Or is it for it to be self contained?

Comment (Bilb) [reply ts/hooks/useDebuncedSpellcheck.ts:37]: If that's the case should we maybe just set the .style property through the ref object? Can we? It's a bit weird to inject styles like this, but idk

**Review by Bilb — APPROVED** [review]

File: ts/hooks/useDebuncedSpellcheck.ts (hunk 1 above)
Comment (Aerilym) [reply ts/hooks/useDebuncedSpellcheck.ts:72]: It was causing issues in my editor, eslint didnt like the fact that debounce isnt trackable

File: ts/hooks/useDebuncedSpellcheck.ts (hunk 2 above)
Comment (Aerilym) [reply ts/hooks/useDebuncedSpellcheck.ts:37]: Would like to keep it self contained, its a bit weird but im not sure you can use the style prop for this? as its all these spelling meta tags?
