### PR TITLE
fix: auto retry forever to push group notification msgs

### LINKED ISSUE #222: [Feature] "preferences" window
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Section of settings named "preferences", where you can modify next preferences being on by default for the conversations:
1. Are messages automatically deleted?
1.5. How fast?
2. Is the ability to receive voice messages on by default?
3. Are reactions you're leaving anonymous by default? 
4. etc

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Bilb**

### CODE REVIEW

File: ts/session/sending/MessageSender.ts [hunk 1]
```diff
@@ -559,6 +560,18 @@ async function sendEncryptedDataToSnode<T extends GroupPubkeyType | PubkeyType>(
     return batchResults;
   } catch (e) {
     window.log.warn(`sendEncryptedDataToSnode failed with ${e.message}`);
+    const sortedSubRequestsWithMsg = sortedSubRequests.filter(r => isStoreUserInitiatedMessage(r));
+    for (let index = 0; index < sortedSubRequestsWithMsg.length; index++) {
+      const request = sortedSubRequestsWithMsg[index];
+      if (request.dbMessageIdentifier) {
+        // eslint-disable-next-line no-await-in-loop
+        await MessageSentHandler.handleSwarmMessageSentFailure(
```
Comment (yougotwill) [inline ts/session/sending/MessageSender.ts:568]: I think you are going to have to explain this to me in person 🦆

**Review by yougotwill — APPROVED** [review]
LGTM 🚢
